### ISSUE TITLE
[BUG] Getting 403 Forbidden error

### ISSUE THREAD

**Issue by furryboy1** [returnrqt/fishstrap#9]
### Fishstrap Version

v2.8.1.5

### What problem did you encounter?

Analyzed the log and it seems the Live bucket is invalid or does not exist. (anymore)
How do i fix this or is it fixable?
Also where is the "Automatic channel change action" i couldn't find it.

### Bloxstrap Log

```text
2024-11-20T21:49:29Z [App::OnStartup] Starting Fishstrap v2.8.1.5
2024-11-20T21:49:29Z [App::OnStartup] Compiled Friday, 15 November 2024 at 7:19:47 PM from LAPTOP-QEOUITOA\Return
2024-11-20T21:49:29Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Fishstrap\Fishstrap.exe
2024-11-20T21:49:29Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Fishstrap
2024-11-20T21:49:29Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-20T21:49:29Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Fishstrap\Logs\Fishstrap_20241120T214929Z.log
2024-11-20T21:49:29Z [Logger::Initialize] Finished initializing!
2024-11-20T21:49:29Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Fishstrap\Settings.json...
2024-11-20T21:49:29Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-20T21:49:29Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Fishstrap\State.json...
2024-11-20T21:49:29Z [JsonManager<State>::Load] Loaded successfully!
2024-11-20T21:49:29Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Fishstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-20T21:49:29Z [FastFlagManager::Load] Loaded successfully!
2024-11-20T21:49:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-20T21:49:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-20T21:49:30Z [LaunchHandler::LaunchRoblox] Creating ROBLOX_singletonMutex
2024-11-20T21:49:30Z [Bootstrapper::Run] Running bootstrapper
2024-11-20T21:49:30Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-20T21:49:30Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-20T21:49:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-20T21:49:30Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-20T21:49:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-20T21:49:31Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-20T21:49:31Z [Bootstrapper::Run] Connectivity check finished
2024-11-20T21:49:31Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-11-20T21:49:31Z [Deployment::GetInfo] Getting deploy info for channel live
2024-11-20T21:49:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/live
2024-11-20T21:49:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/live
2024-11-20T21:49:31Z [RegistryKeyEx::SetValueSafe] Writing 'live' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-20T21:49:31Z [Bootstrapper::GetLatestVersionInfo] fail ch
2024-11-20T21:49:31Z [ApplicationSettings::Fetch.PCClientBootstrapper.live] Fetching fast flags
2024-11-20T21:49:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/live
2024-11-20T21:49:31Z [HttpClientLoggingHandler::ProcessResponse] 403 Forbidden https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/live
2024-11-20T21:49:31Z [Bootstrapper::HandleConnectionError] Connectivity check failed
2024-11-20T21:49:31Z [Bootstrapper::HandleConnectionError] (0x80131500) System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Bloxstrap.RobloxInterfaces.ApplicationSettings.Fetch()
   at Bloxstrap.RobloxInterfaces.ApplicationSettings.GetAsync[T](String name)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Bloxstrap.RobloxInterfaces.ApplicationSettings.Get[T](String name)
   at Bloxstrap.RobloxInterfaces.Deployment.GetLocation(String resource)
   at Bloxstrap.Bootstrapper.GetLatestVersionInfo()
   at Bloxstrap.Bootstrapper.Run()
2024-11-20T21:49:32Z [App::Terminate] Terminating with exit code 1223 (ERROR_CANCELLED)
```

**Comment by returnrqt** [comment]
Try setting your channel to `production` instead of live.

**Comment by furryboy1** [comment]
> Try setting your channel to `production` instead of live.

Okay

**Comment by furryboy1** [comment]
Worked thx
